# Generated by Django 5.2.8 on 2025-12-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0002_prueba1_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='colaboradores',
            fields=[
                ('id_colab', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_nomina', models.IntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('prim_apellido', models.CharField(max_length=200)),
                ('seg_apellido', models.CharField(max_length=200)),
                ('nombre_com', models.CharField(max_length=200)),
                ('extension', models.IntegerField()),
                ('nivel', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba1',
        ),
    ]
