# Generated by Django 5.2.8 on 2025-12-09 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0003_colaboradores_delete_prueba1'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('area', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('num_colabs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='correos',
            fields=[
                ('id_cor', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_c', models.CharField(max_length=200, unique=True)),
                ('cont_c', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cubiculos',
            fields=[
                ('num_c', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_c', models.CharField(max_length=200)),
                ('pasillo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id_equip', models.BigAutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=200, unique=True)),
                ('ip', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='parallels',
            fields=[
                ('id_par', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_p', models.CharField(max_length=200, unique=True)),
                ('cont_p', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='scrit',
            fields=[
                ('id_scit', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_s', models.CharField(max_length=200, unique=True)),
                ('cont_s', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='extension',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='num_nomina',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateField()),
                ('id_colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='correos_colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.colaboradores')),
                ('id_cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.correos')),
            ],
        ),
        migrations.CreateModel(
            name='cubiculo_colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.colaboradores')),
                ('num_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.cubiculos')),
            ],
        ),
        migrations.CreateModel(
            name='equipo_colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.colaboradores')),
                ('id_equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='parallels_colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.colaboradores')),
                ('id_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.parallels')),
            ],
        ),
        migrations.CreateModel(
            name='scrit_colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.colaboradores')),
                ('id_scrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.scrit')),
            ],
        ),
    ]
